sudo: false
language: python
matrix:
  include:
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.5
    env: TOX_ENV=quality
install:
- pip install -r requirements/travis.txt
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
