# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'edx-repo-health'
  description: "edx-repo-health is a set of checks of the health of repositories."
  links:
    - url: "https://github.com/openedx/edx-repo-health"
      title: "edX Repo Health Checks"
      icon: "Web"
  annotations:
    openedx.org/arch-interest-groups: ""
spec:
  owner: group:2u-arbi-bom
  type: 'other'
  lifecycle: 'production'
