name: automerge

# Only trigger, when the Python CI workflow succeeded
on:
  pull_request_review:
    types:
      - submitted
  # check_suite:
  #   types:
  #     - completed
  # status: {}
  workflow_run:
    # using specific workflow to be completed and it review should be submitted
    # CI pipeline contains the unit tests verification
    workflows: ["Python CI"]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: "Ready to Merge"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "5000"
          MERGE_REQUIRED_APPROVALS: "0"
